name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # Daily update (UTC)
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Icons
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.icons.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
